language: php

sudo: false

php:
    - 5.6
    - 7.0

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer install
    - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs

script:
    - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 7.0
          env: SYMFONY_VERSION=3.0.*

notifications:
    email:
        recipients:
            - madmis@inbox.ru
        on_success: never
        on_failure: always

